name: ContiniousIntegrationChecks
run-name: ${{ github.actor }} triggered CI run with event ${{ github.event_name }} for branch ${{ github.ref }}
on:
  push:
    branches: [ main, ci_add]
  pull_request:
    branches_ignore: []
permissions:
  id-token: write
  contents: read # This is required for actions/checkout
jobs:
  fullCI:
    defaults:
      run:
        shell: bash -l {0}
    name: CI test
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The job's status is ${{ job.status }}."
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Set up R env
        uses: r-lib/actions/setup-r@v2
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          python-version: 3.12
          channels: bioconda, conda-forge, defaults
      - name: Conda create env and install dependencies
        shell: bash -l {0}
        run: |
          conda create -n test_r r-base r-devtools r-testthat
          conda activate test_r
          Rscript -e "testthat::test_local()" 
      - name: PreCommit
        uses: pre-commit/action@v3.0.1